name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run tests
      run: ./gradlew check build
      env:
        SimulatedPlatform: "com.pi4j.gpio.extension.mcp.MCP23017GpioProvider"
    - name: Junit Report to Annotations
      uses: ashley-taylor/junit-report-annotations-action@v1.0
      if: always()
      with:
        access-token: ${{ secrets.GITHUB_TOKEN }}
        path: "build/test-results/test/*.xml"
        numFailures: 10
        testSrcPath: "src/test/groovy/"
    - name: Store JAR file as artifact
      uses: actions/upload-artifact@v2-preview
      with:
        name: application
        path: build/libs/*.jar
