name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run tests
      run: ./gradlew check build
    - name: Tag new build
      run: ./gradlew release -Prelease.disableChecks -Prelease.pushTagsOnly -PversionIncrementer=incrementPrerelease
